# Generated by Django 4.0.3 on 2022-03-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(max_length=100)),
                ('asset_no', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_make', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('location_status', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('purchase_reason', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('in_service', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='eq_images/')),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
